// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtqckhbsnlrsciixpbwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cWNraGJzbmxyc2NpaXhwYndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODA1MTksImV4cCI6MjA2OTg1NjUxOX0.8NDL_M4yEZYUfPeysrzDkHweohuMbROyyB-N35NghwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});